// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using TransactionLedger.Models;

namespace TransactionLedger.Migrations
{
    [DbContext(typeof(WoollyBusinessContext))]
    [Migration("20180319000403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TransactionLedger.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfTransaction")
                        .HasColumnType("datetime");

                    b.Property<int>("SupplierId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("TransactionLedger.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("ItemId");

                    b.Property<int>("PurchaseId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseDetail");
                });

            modelBuilder.Entity("TransactionLedger.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime>("DateOfTransaction")
                        .HasColumnType("datetime");

                    b.Property<int>("SaleSourceId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("SaleSourceId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("TransactionLedger.Models.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("ItemId");

                    b.Property<int>("SaleId");

                    b.Property<decimal>("Value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SaleDetail");
                });

            modelBuilder.Entity("TransactionLedger.Models.SaleSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("SaleSource");
                });

            modelBuilder.Entity("TransactionLedger.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("TransactionLedger.Models.Purchase", b =>
                {
                    b.HasOne("TransactionLedger.Models.Supplier", "Supplier")
                        .WithMany("Purchase")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_Purchase_Supplier");
                });

            modelBuilder.Entity("TransactionLedger.Models.PurchaseDetail", b =>
                {
                    b.HasOne("TransactionLedger.Models.Purchase", "Purchase")
                        .WithMany("PurchaseDetail")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_PurchaseDetail_Purchase");
                });

            modelBuilder.Entity("TransactionLedger.Models.Sale", b =>
                {
                    b.HasOne("TransactionLedger.Models.SaleSource", "SaleSource")
                        .WithMany("Sale")
                        .HasForeignKey("SaleSourceId")
                        .HasConstraintName("FK_Sale_SaleSource");
                });

            modelBuilder.Entity("TransactionLedger.Models.SaleDetail", b =>
                {
                    b.HasOne("TransactionLedger.Models.Sale", "Item")
                        .WithMany("SaleDetail")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_SaleDetail_Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
